% This script is used to cluster subjects with psychiatric disorders into subtypes (biotypes) using HYDRA and functional connectivity
% Reference:
%   "HYDRA: Revealing heterogeneity of imaging and genetic patterns
%   through a multiple max-margin discriminative analysis framework."
%   NeuroImage 145 (2017): 346-364.

lc_cluster_hydra('-pd', 'D:\WorkStation_2018\Workstation_2020_transdiagnositic_subtyping\Data\p_test',...
                          '-hd', 'D:\WorkStation_2018\Workstation_2020_transdiagnositic_subtyping\Data\hc_test',... 
                          '-ft', 'fc',...
                          '-ip', 1, '-ec', 0.85,...
                          '-od', 'D:\WorkStation_2018\Workstation_2020_transdiagnositic_subtyping\Data',...
                          '-mincs',2, '-maxcs',10, '-cf', 5);