function lc_dtiMakeDt6FromFsl_batch()
% Make dt6 file from FSL outputs
% This function is based on vistasoft: dtiMakeDt6FromFsl
% Inputs:
%   dti_root: DTI files' root directory, in which contains each subject's files that be generated by FSL (S0.nii.gz)
%   t1_root: T1 files' root directory, in which contains each subject's T1 file.
%   outpath: output directory.
%  Outputs:
%   dt6 files

% Example:
%   dti_root = 'D:\workstation_b\yinyi\AFQ\DTI';
%   t1_root = 'D:\workstation_b\yinyi\AFQ\T1';
%   outpath = 'D:\workstation_b\yinyi\AFQ\dt6';
%   lc_dtiMakeDt6FromFsl_batch(dti_root, t1_root, outpath);

dti_root = uigetdir('*.*','dti_root');
t1_root = uigetdir('*.*','t1_root');
outpath = uigetdir('*.*','outpath');

% Identify S0 and T1
dti_folder = dir(dti_root);
dti_folder = dti_folder(3:end);
dti_subj = fullfile(dti_root, {dti_folder.name})';
n_subj = length(dti_subj);
for i = 1:n_subj
    subj_folder = dir(dti_subj{i});
    subj_file = fullfile(dti_subj{i}, {subj_folder.name});
    subj_native_space = subj_file{end};
    subj_native_space_folder = dir(subj_native_space);
    subj_native_space_file = fullfile(subj_native_space, {subj_native_space_folder.name})';
    loc_s0 = cell2mat(cellfun(@(x) isempty(x), regexp(subj_native_space_file, 'S0.nii'),'UniformOutput',false)) == 0;
    b0FileName = subj_native_space_file{loc_s0};
    % identify t1
    [~, subjname] = fileparts(fileparts(fileparts(b0FileName)));
%     fprintf('Make dt6 file for %d/%d subject (%s)', i/n_subj, subjname);
    t1name_folder = dir(fullfile(t1_root, subjname));
    t1name = fullfile(t1_root, subjname, {t1name_folder.name});
    t1FileName = t1name{end};
    
    % outpath
    outPath = fullfile(outpath, subjname);
    outPathName = fullfile(outpath, subjname, 'dt6.mat');
    if ~exist(outPath,'file')
        mkdir(outPath)
    end
    
    dtiMakeDt6FromFsl(b0FileName, t1FileName,outPathName);
end
fprintf('All Done!\n');
end